name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o website
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: website
        path: website/wwwroot/**
        if-no-files-found: error
    - name: setup git config
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: checkout
      run: |
        # Stage the file, commit and push
        git checkout ghpages
    - name: copy files
      run: cp -r ./website/. ./docs
    - name: commit
      run: |
        # Stage the file, commit and push
        git add ./docs
        git commit -m "Publish Site"
        git push origin ghpages
